// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SalesReturnsSystem.Entities
{
    [Index("CouponIDValue", Name = "UQ_Coupons_CouponIDValue", IsUnique = true)]
    internal partial class Coupon
    {
        public Coupon()
        {
            Sales = new HashSet<Sale>();
        }

        [Key]
        public int CouponID { get; set; }
        [Required(ErrorMessage = "Coupon ID Value is required.")]
        [StringLength(10, ErrorMessage = "Coupon ID Value has a limit of 10 characters.")]
        public string CouponIDValue { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EndDate { get; set; }
        public int CouponDiscount { get; set; }

        [InverseProperty("Coupon")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}