// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SalesReturnsSystem.Entities
{
    internal partial class Position
    {
        public Position()
        {
            Employees = new HashSet<Employee>();
        }

        [Key]
        public int PositionID { get; set; }
        [Required(ErrorMessage = "Description is required.")]
        [StringLength(50, ErrorMessage = "Description has a limit of 50 characters.")]
        public string Description { get; set; }

        [InverseProperty("Position")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}