// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SalesReturnsSystem.Entities
{
    internal partial class Province
    {
        public Province()
        {
            Vendors = new HashSet<Vendor>();
        }

        [Key]
        [StringLength(2, ErrorMessage = "Province ID has a limit of 2 characters.")]
        public string ProvinceID { get; set; }
        [Required(ErrorMessage = "Description is required.")]
        [StringLength(50, ErrorMessage = "Description has a limit of 50 characters.")]
        public string Description { get; set; }

        [InverseProperty("Province")]
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}