// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SalesReturnsSystem.Entities
{
    internal partial class Vendor
    {
        public Vendor()
        {
            StockItems = new HashSet<StockItem>();
        }

        [Key]
        public int VendorID { get; set; }
        [Required(ErrorMessage = "Vendor Name is required.")]
        [StringLength(100, ErrorMessage = "Vendor Name has a limit of 100 characters.")]
        public string VendorName { get; set; }
        [Required(ErrorMessage = "Phone is required.")]
        [StringLength(12, ErrorMessage = "Phone has a limit of 12 characters.")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Address is required.")]
        [StringLength(30, ErrorMessage = "Address has a limit of 30 characters.")]
        public string Address { get; set; }
        [Required(ErrorMessage = "City is required.")]
        [StringLength(50, ErrorMessage = "City has a limit of 50 characters.")]
        [Unicode(false)]
        public string City { get; set; }
        [Required(ErrorMessage = "Province ID is required.")]
        [StringLength(2, ErrorMessage = "Province ID has a limit of 2 characters.")]
        public string ProvinceID { get; set; }
        [Required(ErrorMessage = "Postal Code is required.")]
        [StringLength(6, ErrorMessage = "Postal Code has a limit of 6 characters.")]
        public string PostalCode { get; set; }

        [ForeignKey("ProvinceID")]
        [InverseProperty("Vendors")]
        public virtual Province Province { get; set; }
        [InverseProperty("Vendor")]
        public virtual ICollection<StockItem> StockItems { get; set; }
    }
}